# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/alarcon-osorio/SpringCloudParams
          skipSslValidation: true
          timeout: 4

  # Spring properties
  profiles:
    active: dev